services:
  discovery-server:
    build: ./discoveryserver
    ports:
      - "8888:8888"
    networks:
      - common
  gateway-server:
    build: ./gatewayserver
    ports:
      - "8001:8001"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8888/eureka/
      - EUREKA_URL=http://discovery-server:8888
    depends_on:
      - discovery-server
    networks:
      - common
  config-server:
    build: ./configserver
    ports:
      - "8079:8079"
    networks:
      - common
  customer-service:
    build: ./customerservice
    ports:
      - "8083:8083"
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - CONFIGURL=http://config-server:8079
    # kubernetes
    restart: on-failure # her hata aldığında
    #restart: unless-stopped # kullanıcı dışı bir şekilde durduysa
    #restart: always # kullanıcı dahil herhangi bir şekilde durduysa
    depends_on:
      - postgres
      - discovery-server
      - config-server
    networks:
      - common
  order-service:
    build: ./orderservice
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongodb:27017/orderservice?authSource=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8888/eureka/
    depends_on:
      - mongodb
      - discovery-server
    networks:
      - common
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-volume:/data/db
    networks:
      - common
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    networks:
      - common


volumes:
  postgresql-volume:
    name: postgresql-volume
  mongo-volume:
    name: mongo-volume

networks:
  common:
    driver: bridge
